Repository ironcore-dev/oob, pull requests merged in 2024-02, with the labels that each got.

#117 Fix actions
  .github/workflows/golangci-lint.yml
  .github/workflows/publish-docker.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test.yml
Labels: bug, enhancement

#119 Move OOB from onmetal to ironcore-dev
  .github/workflows/publish-docker.yml
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/v1alpha1/groupversion_info.go
  applyconfiguration/api/v1alpha1/oob.go
  applyconfiguration/internal/internal.go
  applyconfiguration/utils.go
  bmc/bmc.go
  bmc/ipmi.go
  bmc/redfish.go
  bmc/ssh.go
  config/console/kustomization.yaml
  config/crd/bases/ironcore.dev_oobs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_oobs.yaml
  config/crd/patches/webhook_in_oobs.yaml
  config/default/kustomization.yaml
  config/manager/controller_manager_config.yaml
  config/manager/manager.yaml
  config/rbac/oob_editor_role.yaml
  config/rbac/oob_viewer_role.yaml
  config/rbac/role.yaml
  controllers/controllers_test.go
  controllers/ip_controller.go
  controllers/ip_controller_test.go
  controllers/oob_controller.go
  docs/README.md
  go.mod
  go.sum
  hack/generate.sh
  hack/macPrefixes.yaml
  main.go
  openapi/api_violations.report
  openapi/zz_generated.openapi.go
  servers/console_server.go
Labels: documentation

#123 Fix deployment
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
Labels: bug

#129 Switch to public `ipam` reference
  .github/workflows/golangci-lint.yml
  .github/workflows/publish-docker.yml
  .github/workflows/test.yml
  controllers/controllers_test.go
  controllers/ip_controller.go
  controllers/ip_controller_test.go
  go.mod
  go.sum
  main.go
Labels: enhancement
